In [1]:
import pandas as pd

In [4]:
df = pd.read_parquet(r'C:\projects\binance-dowloader-3.0\data (1).parquet')
df

,timestamp,time,id,price,qty,quote_qty,is_buyer_maker
0,2026-02-01 00:00:00.106000+00:00,1769904000106,1818927320,0.2933,192.0,56.313599,True
1,2026-02-01 00:00:00.116000+00:00,1769904000116,1818927321,0.2933,128.0,37.542400,True
2,2026-02-01 00:00:01.922000+00:00,1769904001922,1818927322,0.2933,170.0,49.861000,True
3,2026-02-01 00:00:02.126000+00:00,1769904002126,1818927323,0.2933,110.0,32.263000,True
4,2026-02-01 00:00:02.137000+00:00,1769904002137,1818927324,0.2933,490.0,143.716995,True
...,...,...,...,...,...,...,...
781197,2026-02-01 23:59:58.785000+00:00,1769990398785,1819710543,0.2856,21.0,5.997600,False
781198,2026-02-01 23:59:59.809000+00:00,1769990399809,1819710544,0.2856,36.0,10.281600,False
781199,2026-02-01 23:59:59.809000+00:00,1769990399809,1819710545,0.2856,40.0,11.424000,False
781200,2026-02-01 23:59:59.910000+00:00,1769990399910,1819710546,0.2856,18.0,5.140800,False
781201,2026-02-01 23:59:59.910000+00:00,1769990399910,1819710547,0.2856,69.0,19.706400,False

In [3]:
df = pd.read_csv(r'C:\projects\binance-dowloader-3.0\ADAUSDT-trades-2026-04-18.csv')
df

                id   price      qty  quote_qty           time  is_buyer_maker
0       1858544475  0.2585   8518.0  2201.9030  1776470400181            True
1       1858544476  0.2585   6650.0  1719.0250  1776470400318            True
2       1858544477  0.2585  23559.0  6090.0015  1776470400399            True
3       1858544478  0.2585     22.0     5.6870  1776470400399            True
4       1858544479  0.2585     43.0    11.1155  1776470400399            True
...            ...     ...      ...        ...            ...             ...
378723  1858924770  0.2490   1588.0   395.4120  1776556799570           False
378724  1858924771  0.2490   2007.0   499.7430  1776556799570           False
378725  1858924772  0.2489     21.0     5.2269  1776556799575            True
378726  1858924773  0.2490   1935.0   481.8150  1776556799591           False
378727  1858924774  0.2490    400.0    99.6000  1776556799614           False

[378728 rows x 6 columns]